// Map of email domains to university names
const domainToUniversity: Record<string, string> = {
  'syracuse.edu': 'Syracuse University',
  'usc.edu': 'University of Southern California',
  'northeastern.edu': 'Northeastern University',
  'nyu.edu': 'New York University',
  'bu.edu': 'Boston University',
  'ucla.edu': 'University of California, Los Angeles',
  'berkeley.edu': 'UC Berkeley',
  'stanford.edu': 'Stanford University',
  'mit.edu': 'MIT',
  'harvard.edu': 'Harvard University',
  'yale.edu': 'Yale University',
  'princeton.edu': 'Princeton University',
  'columbia.edu': 'Columbia University',
  'upenn.edu': 'University of Pennsylvania',
  'umich.edu': 'University of Michigan',
  'uchicago.edu': 'University of Chicago',
  'gatech.edu': 'Georgia Tech',
  'utexas.edu': 'University of Texas at Austin',
  'unc.edu': 'University of North Carolina',
  'ufl.edu': 'University of Florida',
  'osu.edu': 'Ohio State University',
  'psu.edu': 'Penn State University',
  'uw.edu': 'University of Washington',
  'umd.edu': 'University of Maryland',
  'rutgers.edu': 'Rutgers University',
  'asu.edu': 'Arizona State University',
  'uva.edu': 'University of Virginia',
  'duke.edu': 'Duke University',
  'northwestern.edu': 'Northwestern University',
  'cornell.edu': 'Cornell University',
  'brown.edu': 'Brown University',
  'dartmouth.edu': 'Dartmouth College',
  'cmu.edu': 'Carnegie Mellon University',
  'georgetown.edu': 'Georgetown University',
  'tufts.edu': 'Tufts University',
  'bc.edu': 'Boston College',
  'wustl.edu': 'Washington University in St. Louis',
  'emory.edu': 'Emory University',
  'rice.edu': 'Rice University',
  'vanderbilt.edu': 'Vanderbilt University',
  'wisc.edu': 'University of Wisconsin-Madison',
  'umn.edu': 'University of Minnesota',
  'purdue.edu': 'Purdue University',
  'indiana.edu': 'Indiana University',
  'msu.edu': 'Michigan State University',
  'uiuc.edu': 'University of Illinois Urbana-Champaign',
  'illinois.edu': 'University of Illinois Urbana-Champaign',
  'tamu.edu': 'Texas A&M University',
  'fsu.edu': 'Florida State University',
  'vt.edu': 'Virginia Tech',
  'clemson.edu': 'Clemson University',
  'lsu.edu': 'Louisiana State University',
  'baylor.edu': 'Baylor University',
  'miami.edu': 'University of Miami',
  'tulane.edu': 'Tulane University',
  'smu.edu': 'Southern Methodist University',
  'gwu.edu': 'George Washington University',
  'american.edu': 'American University',
  'drexel.edu': 'Drexel University',
  'temple.edu': 'Temple University',
  'villanova.edu': 'Villanova University',
  'lehigh.edu': 'Lehigh University',
  'fordham.edu': 'Fordham University',
  'nau.edu': 'Northern Arizona University',
  'colorado.edu': 'University of Colorado Boulder',
  'oregonstate.edu': 'Oregon State University',
  'uoregon.edu': 'University of Oregon',
};

export function detectUniversityFromEmail(email: string): string | null {
  const domain = email.split('@')[1]?.toLowerCase();
  if (!domain) return null;
  
  // Direct match
  if (domainToUniversity[domain]) return domainToUniversity[domain];
  
  // Check if it's any .edu domain (likely a university)
  if (domain.endsWith('.edu')) {
    // Try to generate a name from the domain
    const name = domain.replace('.edu', '');
    return null; // Return null so user can manually select
  }
  
  return null;
}

export function isEduEmail(email: string): boolean {
  const domain = email.split('@')[1]?.toLowerCase();
  return domain?.endsWith('.edu') || false;
}

// Common universities for dropdown selection
export const universityList: string[] = [
  'Arizona State University',
  'Baylor University',
  'Boston College',
  'Boston University',
  'Brown University',
  'Carnegie Mellon University',
  'Clemson University',
  'Columbia University',
  'Cornell University',
  'Dartmouth College',
  'Drexel University',
  'Duke University',
  'Emory University',
  'Florida State University',
  'Fordham University',
  'George Washington University',
  'Georgetown University',
  'Georgia Tech',
  'Harvard University',
  'Indiana University',
  'Louisiana State University',
  'Lehigh University',
  'MIT',
  'Michigan State University',
  'New York University',
  'Northeastern University',
  'Northwestern University',
  'Ohio State University',
  'Oregon State University',
  'Penn State University',
  'Princeton University',
  'Purdue University',
  'Rice University',
  'Rutgers University',
  'Southern Methodist University',
  'Stanford University',
  'Syracuse University',
  'Temple University',
  'Texas A&M University',
  'Tufts University',
  'Tulane University',
  'UC Berkeley',
  'University of California, Los Angeles',
  'University of Chicago',
  'University of Colorado Boulder',
  'University of Florida',
  'University of Illinois Urbana-Champaign',
  'University of Maryland',
  'University of Miami',
  'University of Michigan',
  'University of Minnesota',
  'University of North Carolina',
  'University of Oregon',
  'University of Pennsylvania',
  'University of Southern California',
  'University of Texas at Austin',
  'University of Virginia',
  'University of Washington',
  'University of Wisconsin-Madison',
  'Vanderbilt University',
  'Villanova University',
  'Virginia Tech',
  'Washington University in St. Louis',
  'Yale University',
].sort();
